---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "nginx-1-config-86vx"
  namespace: "default"
  labels:
    app: "nginx-1"
data:
  kubecloud_mykey01: "MyValue01"
  kubecloud_mykey02: "MyValue02"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-1"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx-1"
  template:
    metadata:
      labels:
        app: "nginx-1"
    spec:
      containers:
      - name: "nginx-1"
        image: "nginx:latest"
        env:
        - name: "kubecloud_mykey01"
          valueFrom:
            configMapKeyRef:
              key: "kubecloud_mykey01"
              name: "nginx-1-config-86vx"
        - name: "kubecloud_mykey02"
          valueFrom:
            configMapKeyRef:
              key: "kubecloud_mykey02"
              name: "nginx-1-config-86vx"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nginx-1-hpa-polm"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "nginx-1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
